repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-ast
      - id: check-merge-conflict
      - id: check-toml
      # - id: check-yaml
      - id: end-of-file-fixer
        files: \.py$
      - id: trailing-whitespace
        files: \.py$
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        exclude: 'warp_maniskill/.*|docs/.*|examples/.*'
        args:
          - --line-length=88
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: 'warp_maniskill/.*|docs/.*|examples/.*'
        args:
          - --profile=black
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        exclude: 'warp_maniskill/.*|docs/.*|examples/.*'
        args:
          - -r
          - --in-place
          - --remove-unused-variables
          # - --remove-all-unused-imports