# .readthedocs.yaml
# Read the Docs configuration file

# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
sphinx:
  configuration: docs/source/conf.py

python:
   install:
    - method: pip
      path: .