[build-system]
requires = ["setuptools>=62.3.0"]
build-backend = "setuptools.build_meta"

[tool.black]
line_length = 88     # default
extend-exclude = '''^/warp_maniskill|^/docs'''


[tool.isort]
profile = "black"
skip_glob = ["*/build/*", "*/warp_maniskill/*", "*/docs/*", "*/data/*", "*/demos/*"]