python map_rl/train_ppo.py \
    --env_id=PickCubeDiscreteInit-v1 \
    --robot_uids=xarm6_robotiq \
    --control_mode=pd_joint_vel \
    --exp_name=PickCube_xarm6_ppo \
    --num_envs=50 \
    --num_eval_envs=20 \
    --eval_freq=20 \
    --total_timesteps=100_000_000 \
    --num_steps=100 \
    --gamma=0.9 \
    --capture-video \
    --track \
    --wandb_project_name "ManiSkill-RL"