_wandb:
    value:
        cli_version: 0.21.0
        code_path: code/examples/baselines/ppo/ppo_rgb.py
        e:
            7ds85azqmm4a3wyn5f4zkkzvfx8g8fcv:
                args:
                    - --env_id=PickCube-v1
                    - --robot_uids=xarm6_robotiq
                    - --control_mode=pd_joint_vel
                    - --exp_name=PickCubeMatched3_xarm6_robotiq_jv_ppo_rgb_3
                    - --num_envs=512
                    - --num_eval_envs=8
                    - --eval_freq=20
                    - --total_timesteps=100_000_000
                    - --num_steps=50
                    - --num_minibatches=32
                    - --num_eval_steps=50
                    - --gamma=0.8
                    - --update_epochs=4
                    - --capture-video
                    - --track
                    - --wandb_project_name
                    - '"ManiSkill-RL"'
                codePath: examples/baselines/ppo/ppo_rgb.py
                codePathLocal: examples/baselines/ppo/ppo_rgb.py
                cpu_count: 24
                cpu_count_logical: 32
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "1006450962432"
                        used: "728072884224"
                email: w5chung@ucsd.edu
                executable: /home/woojeh/miniconda3/envs/icra2025/bin/python
                git:
                    commit: 8234fd6f5b3cf7cf795664b692f2ac9149aee264
                    remote: https://github.com/mastee7/ManiSkill.git
                gpu: NVIDIA GeForce RTX 4080 SUPER
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 10240
                      memoryTotal: "17171480576"
                      name: NVIDIA GeForce RTX 4080 SUPER
                      uuid: GPU-b71e745e-26d1-4a4d-fa68-49cdaf084725
                host: woojeh-Alienware-Aurora-R16
                memory:
                    total: "33383632896"
                os: Linux-6.8.0-60-generic-x86_64-with-glibc2.35
                program: /home/woojeh/Documents/ICRA2025/ManiSkill/examples/baselines/ppo/ppo_rgb.py
                python: CPython 3.10.18
                root: /home/woojeh/Documents/ICRA2025/ManiSkill
                startedAt: "2025-07-23T21:14:28.384616Z"
                writerId: 7ds85azqmm4a3wyn5f4zkkzvfx8g8fcv
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 49
            "2":
                - 1
                - 49
            "3":
                - 13
                - 15
                - 16
                - 61
            "4": 3.10.18
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
anneal_lr:
    value: false
batch_size:
    value: 25600
capture_video:
    value: true
checkpoint:
    value: null
clip_coef:
    value: 0.2
clip_vloss:
    value: false
control_mode:
    value: pd_joint_vel
cuda:
    value: true
ent_coef:
    value: 0
env_cfg:
    value:
        control_mode: pd_joint_vel
        env_horizon: 50
        env_id: PickCube-v1
        num_envs: 512
        obs_mode: rgb
        partial_reset: true
        render_mode: all
        reward_mode: normalized_dense
        robot_uids: xarm6_robotiq
        sim_backend: physx_cuda
env_id:
    value: PickCube-v1
eval_env_cfg:
    value:
        control_mode: pd_joint_vel
        env_horizon: 50
        env_id: PickCube-v1
        num_envs: 8
        obs_mode: rgb
        partial_reset: true
        render_mode: all
        reward_mode: normalized_dense
        robot_uids: xarm6_robotiq
        sim_backend: physx_cuda
eval_freq:
    value: 20
eval_partial_reset:
    value: false
eval_reconfiguration_freq:
    value: 1
evaluate:
    value: false
exp_name:
    value: PickCubeMatched3_xarm6_robotiq_jv_ppo_rgb_3
finite_horizon_gae:
    value: false
gae_lambda:
    value: 0.9
gamma:
    value: 0.8
include_state:
    value: true
learning_rate:
    value: 0.0003
max_grad_norm:
    value: 0.5
minibatch_size:
    value: 800
norm_adv:
    value: true
num_envs:
    value: 512
num_eval_envs:
    value: 8
num_eval_steps:
    value: 50
num_iterations:
    value: 3906
num_minibatches:
    value: 32
num_steps:
    value: 50
partial_reset:
    value: true
reconfiguration_freq:
    value: null
render_mode:
    value: all
reward_scale:
    value: 1
robot_uids:
    value: xarm6_robotiq
save_model:
    value: true
save_train_video_freq:
    value: null
seed:
    value: 1
target_kl:
    value: 0.2
torch_deterministic:
    value: true
total_timesteps:
    value: 100000000
track:
    value: true
update_epochs:
    value: 4
vf_coef:
    value: 0.5
wandb_entity:
    value: null
wandb_group:
    value: PPO
wandb_project_name:
    value: '"ManiSkill-RL"'
